

export default  {
    products:[
        
        {
        _id: '1',
        name: 'Nike chaussure 1',
        category: 'Chaussures',
        image: "/images/1.jpg",
        prix: 100,
        marque: ' Nike ',
        rating: 4,
        numReviews: 20 ,
    },
    {
        _id: '2',
        name: 'Nike chaussure 2',
        category: 'Chaussures',
        image: "/images/2.jpg",
        prix: 120,
        marque: ' Nike ',
        rating: 4,
        numReviews: 10 ,
    },
    {
        _id: '3',
        name: 'Nike chaussure 3',
        category: 'Chaussures',
        image: "/images/3.jpg",
        prix: 120,
        marque: ' Nike ',
        rating: 3,
        numReviews: 10 ,
    },
    {
        _id: '4',
        name: 'Nike chaussure 4',
        category: 'Chaussures',
        image: "/images/4.jpg",
        prix: 50,
        marque: ' Nike ',
        rating: 4,
        numReviews: 10 ,
    },
    {
        _id: '5',
        name: 'Nike chaussure 5',
        category: 'Chaussures',
        image: "/images/5.jpg",
        prix: 150,
        marque: ' Nike ',
        rating: 3,
        numReviews: 10 ,
    },
    {
        _id: '6',
        name: 'Nike chaussure 6',
        category: 'Chaussures',
        image: "/images/6.jpg",
        prix: 150,
        marque: ' Nike ',
        rating: 5,
        numReviews: 10 ,
    },
    {
        _id: '7',
        name: 'Nike chaussure 7',
        category: 'Chaussures',
        image: "./images/7.jpg",
        prix: 150,
        marque: ' Nike ',
        rating: 5,
        numReviews: 10 ,
    },
    {
        _id: '23',
        name: 'Nike chaussure 23',
        category: 'Chaussures',
        image: "./images/23.jpg",
        prix: 1500,
        marque: ' Nike ',
        rating: 5,
        numReviews: 10 ,
    },
    {
        _id: '24',
        name: 'Nike chaussure 24',
        category: 'Chaussures',
        image: "./images/24.jpg",
        prix: 1500,
        marque: ' Nike ',
        rating: 5,
        numReviews: 10 ,
    },
    {
        _id: '25',
        name: 'Nike chaussure 25',
        category: 'Chaussures',
        image: "./images/25.jpg",
        prix: 1500,
        marque: ' Nike ',
        rating: 5,
        numReviews: 10 ,
    },
    {
        _id: '26',
        name: 'Nike chaussure 26',
        category: 'Chaussures',
        image: "./images/26.jpg",
        prix: 1500,
        marque: ' Nike ',
        rating: 5,
        numReviews: 10 ,
    },
    
]
}